version: '3'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mongo
    ports:
      - "27017:27017"