name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |

            cd /home/ubuntu/Real-Time-Weather-Data-and-intelligent-Crop-Advisory-System
            git pull origin main

            # Backend
            cd server
            npm install
            pm2 restart weather-app || pm2 start index.js --name weather-app
            pm2 save

            # Frontend
            cd ../client
            npm install
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/